"""some changes

Revision ID: 18913db72047
Revises: a9a1e85b98c7
Create Date: 2023-01-12 16:17:46.527027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18913db72047'
down_revision = 'a9a1e85b98c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('course_users',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('fs_path', sa.String(length=100), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('class_users')
    op.drop_table('classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='classes_school_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classes_pkey'),
    sa.UniqueConstraint('join_code', name='classes_join_code_key'),
    sa.UniqueConstraint('slug', name='classes_slug_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('class_users',
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='class_users_class_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='class_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('class_id', 'user_id', name='class_users_pkey')
    )
    op.drop_table('projects')
    op.drop_table('course_users')
    op.drop_table('courses')
    op.drop_table('assignments')
    # ### end Alembic commands ###
