"""dep version

Revision ID: 31dce1bc1cf2
Revises: bcbec4cfae3d
Create Date: 2023-02-21 10:07:09.059352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dce1bc1cf2'
down_revision = 'bcbec4cfae3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_version')
    # ### end Alembic commands ###
