"""empty message

Revision ID: 435948c40a16
Revises: 6e6472af9cd9
Create Date: 2023-01-22 22:29:38.941217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435948c40a16'
down_revision = '6e6472af9cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_email', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['provider_email'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('provider_email')

    # ### end Alembic commands ###
