"""empty message

Revision ID: 53296bf3124e
Revises: 
Create Date: 2023-01-31 22:52:52.462452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53296bf3124e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_email', sa.String(), nullable=True))
        batch_op.drop_constraint('flask_dance_oauth_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['provider_email'], ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('flask_dance_oauth_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('provider_email')

    # ### end Alembic commands ###
