"""some changes 2

Revision ID: 815433af8fde
Revises: 18913db72047
Create Date: 2023-01-17 10:14:27.737421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815433af8fde'
down_revision = '18913db72047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth')
    # ### end Alembic commands ###
