"""fixing oauth again

Revision ID: aa69804a32f3
Revises: 52c12ec7707d
Create Date: 2023-01-22 22:49:41.788694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa69804a32f3'
down_revision = '52c12ec7707d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.drop_constraint('flask_dance_oauth_provider_email_key', type_='unique')
        batch_op.drop_constraint('flask_dance_oauth_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('provider_email')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider_email', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('flask_dance_oauth_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('flask_dance_oauth_provider_email_key', ['provider_email'])

    # ### end Alembic commands ###
