"""some changes 2 (--slug)

Revision ID: e5189cf67189
Revises: a89ac583cd67
Create Date: 2023-01-21 22:52:15.925556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5189cf67189'
down_revision = 'a89ac583cd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('courses_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint('schools_slug_key', type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_slug_key', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_slug_key', ['slug'])

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('schools_slug_key', ['slug'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('projects_slug_key', ['slug'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('courses_slug_key', ['slug'])

    # ### end Alembic commands ###
