"""empty message

Revision ID: f2579f82ee46
Revises: 4ef3f4e47987
Create Date: 2023-02-07 22:53:31.925022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2579f82ee46'
down_revision = '4ef3f4e47987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object', sa.String(length=255), nullable=False))
        batch_op.drop_column('bucket')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bucket', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('object')

    # ### end Alembic commands ###
