from .models import Assignment, Course, File, Project, School, User
from .connection import ma


# I wish this s*** was autogenerated


class AssignmentSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Assignment
        include_relationships = True
        load_instance = True
        include_fk = True


assignment_schema = AssignmentSchema()


class CourseSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Course
        load_instance = True
        include_fk = True


course_schema = CourseSchema()


class FileSchema(ma.Schema):
    class Meta:
        model = File
        load_instance = True
        include_fk = True


file_schema = FileSchema()


class ProjectSchema(ma.Schema):
    class Meta:
        model = Project
        load_instance = True
        include_fk = True
        include_relationships = True


project_schema = ProjectSchema()


class SchoolSchema(ma.Schema):
    class Meta:
        model = School
        load_instance = True
        include_fk = True
        include_relationships = False


school_schema = SchoolSchema()


class UserSchema(ma.Schema):
    class Meta:
        model = User
        load_instance = True
        include_fk = True
        include_relationships = True  # expensive but hopefully worth it


user_schema = UserSchema()
